### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by anujjoshi63** [zeno-oss/productiv#6]
- [ ] desktop: login
- [ ] desktop: show start and end time both
- [ ] desktop: center the modal
- [ ] desktop: cross show with title
- [ ] desktop: modal start time = current time and end time = endTime
- [ ] desktop: time picker show native time popup
- [ ] desktop: title, description, time, label, shade will be the sequence
- [ ] mobile: add asterisk if field is required
- [ ] mobile: done section add "mark as undone" button
- [ ] desktop: Modal "mark as undone" should reflect state
- [ ] desktop: Date formatting
- [ ] mobile: dont show subtitle. "you have n tasks"
- [ ] both: search option to filter using a keyword. title, description, and labels
- [ ] mobile: fix notes main page ui
- [ ] both: expanded view show edit and delete icons
- [ ] both: clicked on label should automatically add a search query
- [ ] both: allow uploading 5 images
- [ ] both: show image carousels
- [ ] both: use dayjs
- [ ] both: show indication that a note contains image(s)
- [ ] both: implement pin notes feature
- [ ] both: implement tesseract
- [ ] mobile: use HeroIcon
- [ ] mobile: expanded view for Tasks and Notes
- [ ] both: show '...' for overflowing labels and text
- [ ] mobile: we have Skia for drawing image on canvas

**Comment by shiroyasha9** [comment]
@anujjoshi63 instead of removing the "you have n tasks" subtitle altogether on the DoneTaskScreen, let's instead show "Completed n tasks"

**Comment by shiroyasha9** [comment]
icons to be used:

- plus for AddTask and AddNote icons (outlined)
- check-circle for completed task icon (outlined)
- pencil-square for edit icon (solid)
- trash for delete icon (solid)
- clock for time in TaskCard (outline)
- calendar for date in TaskCard (outline)

**Comment by anujjoshi63** [comment]
> @anujjoshi63 instead of removing the "you have n tasks" subtitle altogether on the DoneTaskScreen, let's instead show "Completed n tasks" <img alt="image" width="301" src="https://user-images.githubusercontent.com/48734821/226491610-5bf66475-ff56-4f0f-97f3-c113eeb418e6.png">

addressed

**Comment by anujjoshi63** [comment]
@shiroyasha9 pass "ALL" to `getTasks` to get all tasks. Then apply the required filters. Here's how I did it:

```js
tasks.filter(
  (task) => task.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
  task.description?.toLowerCase().includes(searchQuery.toLowerCase()) ||
  task.labels?.toLowerCase().includes(searchQuery.toLowerCase()
)
```
